### PR TITLE
Update scaffold

### PR DESCRIPTION
**Pull request by arnaud-morvan**
Add c2cgeoform_* routes, to be registered using `config.include('c2cgeoform.routes)`.
Update scaffold `initdb` and `/exacation` works.
Add new button in index.pt.

### CODE REVIEW

**Comment by arnaud-morvan** [comment]
@cmangeat : can you have a look ? Here I give optional standard routes in c2cgeoform, that seems more understandable regarding the templates in c2cgeoform. The scaffold works now. User should take care of registering c2cgeoform routes manually after his own routes that match /{table}. You could have a look in the scaffold.

**Comment by cmangeat** [comment]
https://github.com/camptocamp/c2cgeoportal/commit/712f2f69108460f2cdd245497f1660cf4bb62569
https://github.com/camptocamp/c2cgeoform/commit/cf9af5b07171e7265707b211b04bd22df7a78aa7
to discuss...

dbmerge does merge or add,
could go back to index once existing edited or new edited,
but prefer to go back to view/edit details when submit,
problem is that submit for new don't know id for url as db merge/add not yet called,
so have to redirect.

with commit abstract_view_test degraded and form() called twice, once before redirection, and once for view (after redirection.

**Comment by arnaud-morvan** [comment]
Can you please use pull requests, this is a already a pull request, I would like to fix it before merging

**Comment by arnaud-morvan** [comment]
I would like to restore standard workflow with CI (travis) with green status

**Comment by arnaud-morvan** [comment]
not sure to understand your comments, seems that travis problem do not really comes from your commits

**Comment by arnaud-morvan** [comment]
> dbmerge  does merge or add,

what is dbmerge ?

> could  go back to index once existing edited or new edited,
> but prefer to go back to view/edit details when submit,
> problem is that submit for new don't know id for url as db merge/add not yet called,
> so have to redirect.

object id should be updated after sqlalchemy dbsession flush (from serial sequence)
may you use dbsession.flush()  #  this is not a commit but flush pending requests to server
dbsession.expire(object)  # I think you do not need this

**Comment by arnaud-morvan** [comment]
commit is made after request success (pyramid_tm behavior)
but you should be able to get object.id after any flush, even in a transaction, sequence number should be unique.

**Comment by arnaud-morvan** [comment]
sorry for the noise, I do not understand the travis error, everything seems to go fine with checks and tests locally with this PR

**Comment by arnaud-morvan** [comment]
you may have a look to dbsession.flush() : http://docs.sqlalchemy.org/en/latest/orm/session_api.html#sqlalchemy.orm.session.Session.flush

**Pull request merged**
