### PR TITLE
ColanderAlchemy >= 0.3.2 is required

### LINKED ISSUE #91: Use ColanderAlchemy 0.3.2
https://github.com/camptocamp/c2cgeoform/pull/89 required a change to ColanderAlchemy. That change is merged into ColanderAlchemy's master branch, but there's no new release yet. When ColanderAlchemy 0.3.2 is released we need to use `ColanderAlchemy >= 0.3.2` in `setup.py`.

### PR DESCRIPTION
**Pull request by elemoine**
Fixes #91

### CODE REVIEW

**Comment by tsauerwein** [comment]
Thanks, please merge.

**Comment by elemoine** [comment]
@arnaud-morvan you can now use ColanderAlchemy 0.3.2.post1 in your project.i

**Comment by arnaud-morvan** [comment]
DPFE does not work correctly with ColanderAlchemy 0.3.2.post1

Error raised when no file selected in emprise form
Work well with -e https://github.com/stefanofontanelli/ColanderAlchemy@be6e1157415e787e91d10553f6cbdfb4a00350c3#egg=ColanderAlchemy

**Comment by elemoine** [comment]
Argh, I'll need to reproduce this. Can we look at this together on Wednesday?

**Comment by arnaud-morvan** [comment]
I have'nt deeply inspected, I'm not blocked for the moment.
But it would be good to take look at this soon, ok for me wednesday.

**Pull request merged**
